# Generated by Django 4.0.5 on 2022-08-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookId', models.AutoField(primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=500)),
                ('authorName', models.CharField(max_length=500)),
            ],
        ),
    ]
