version: '3.9'
services:
  django:
    image: django-docker:0.0.1
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_URL: ${DB_URL}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
