# Generated by Django 3.1.2 on 2022-08-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countryapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='ISO_A3',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
