# Generated by Django 4.0.5 on 2022-08-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('newsId', models.AutoField(primary_key=True, serialize=False)),
                ('newsTitle', models.CharField(max_length=500)),
                ('readerName', models.CharField(max_length=500)),
            ],
        ),
    ]
